cli: `testsys status` update
bottlerocket-os/bottlerocket-test-system pull request #275
Opened 2022-01-28 18:27 UTC by ecpullen

**Issue number:**
Closes #265 

**Description of changes:**
Provides a clean output for `testsys status`.

**Testing done:**
```
┌────────────────────────┬────────────┬───────────┬────────┬─────────┬────────┐
│          Name          │    Type    │   State   │ Passed │ Skipped │ Failed │
├────────────────────────┼────────────┼───────────┼────────┼─────────┼────────┤
│       Controller       │ Controller │  Running  │        │         │        │
├────────────────────────┼────────────┼───────────┼────────┼─────────┼────────┤
│      testsys-test      │  Resource  │ completed │        │         │        │
├────────────────────────┼────────────┼───────────┼────────┼─────────┼────────┤
│ testsys-test-instances │  Resource  │ completed │        │         │        │
├────────────────────────┼────────────┼───────────┼────────┼─────────┼────────┤
│       ecs-smoke        │    Test    │  passed   │   1    │    0    │   0    │
└────────────────────────┴────────────┴───────────┴────────┴─────────┴────────┘
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-02-07 22:22 UTC, webern requested changes
We've had an out-of-band discussion and arrived at something simpler. The `--wait` use case is fuzzy and our implementation is awkward. So we can simplify things significantly

- We should eliminate the `--wait` argument and functionality.
- `testsys status` always exists 0 (unless it has encountered an error in it's execution)
- We don't need to do anything with resetting the cursor.
- We can keep the work you've done to find the terminal size and use it to format a table, all of that still leads to nice output when `--json` is not used.

2022-02-08 17:29 UTC, ecpullen commented
^ Removes the wait flag from the command and sets the command to always exit 0.

2022-02-08 21:19 UTC, webern approved these changes
😎

2022-02-08 22:06 UTC, etungsten approved these changes

2022-02-08 22:06 UTC, etungsten commented on testsys/src/error.rs
> +    TerminalSize { source: std::io::Error },
Do we still need these errors variants?

2022-02-08 22:06 UTC, etungsten commented on testsys/tests/cli_test.rs
> +    tokio::time::sleep(tokio::time::Duration::from_millis(100)).await;
nit: This seems extraneous if we're waiting later in the loop anyways, could wait first in the loop before doing the assertion.

2022-02-08 22:06 UTC, etungsten commented on testsys/src/status.rs
> +    fn draw(&self) {
Good job figuring this out! But it almost makes me wonder if there are other crates out there we can use to do this.

2022-02-08 23:10 UTC, merged