cli: `restart test`
bottlerocket-os/bottlerocket-test-system pull request #342
Opened 2022-03-03 19:51 UTC by ecpullen

**Issue number:**

#340 

**Description of changes:**

Adds `testsys restart test <test-name>`. This command deletes the test object and then re-creates it.

**Testing done:**

Ran `testsys run aws-k8s ...` and after test completion used `testsys restart test ...` and the sonobuoy test was deleted and a new one was started.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-03-03 20:01 UTC, webern requested changes
Nice, that was fast. We need to obliterate the `status` otherwise I think the controller wouldn't see this as a new test.

2022-03-03 20:01 UTC, webern commented on testsys/src/restart_test.rs
> +        test.metadata.resource_version = None;
You also need to set `test.status` to `None`.

2022-03-03 20:48 UTC, ecpullen commented on testsys/src/restart_test.rs
> +        test.metadata.resource_version = None;
The status is automatically reset.

2022-03-03 20:55 UTC, webern commented on testsys/src/restart_test.rs
> +        test.metadata.resource_version = None;
Oh. Well, I guess it would make me feel better to see it even if it is not strictly necessary.

2022-03-03 22:18 UTC, ecpullen commented
^ reset `test.status`

2022-03-04 03:53 UTC, webern approved these changes

2022-03-04 20:06 UTC, etungsten approved these changes

2022-03-04 21:38 UTC, merged