build: bottlerocket-test-tools
bottlerocket-os/bottlerocket-test-system pull request #389
Opened 2022-05-04 21:17 UTC by webern

Move the third party test binaries to their own container image build.

**Issue number:**

Fixes #335

**Description of changes:**

We separate concerns by moving the Go-tools builds to their own `Dockerfile`.
This image will be published to ECR public so that we do not have to build these tools and extract their licenses each time we build our agent containers.

**Testing done:**

Working on it.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-05-05 19:58 UTC, webern commented
^ rebase

2022-05-05 19:59 UTC, webern commented
^ rebase

2022-05-06 00:09 UTC, webern commented
^ rebase

2022-05-06 00:23 UTC, webern commented
^ add a changelog file for the tools directory

2022-05-06 21:17 UTC, webern commented
^ push the date in the changelog

2022-05-09 16:09 UTC, etungsten requested changes

2022-05-09 16:09 UTC, etungsten commented on aws-iam-authenticator_0.5.3.tar.gz
> +<?xml version="1.0" encoding="UTF-8"?>
This file doesn't look like it should be here. Failed curl?

2022-05-09 16:09 UTC, etungsten commented on tools/Dockerfile
> +ARG EKSCTL_VERSION=0.82.0
non-blocking: before pushing to public ECR, please bump this to the latest version.

2022-05-09 16:09 UTC, etungsten commented on tools/Dockerfile
> +ARG SONOBUOY_VERSION=0.53.2
non-blocking: please bump this to the latest version before cutting a release of the tools container image.

2022-05-09 16:32 UTC, webern commented
^ updated versions of eksctl and sonobuoy, but the go builds broke! working on it.

2022-05-09 17:35 UTC, webern commented
^ gitignore tar files and attempt to fix the eksctl build

2022-05-09 20:13 UTC, jpculp requested changes
You'll need to add the following to `tools/clarify.toml`:
```
[clarify."github.com/dave/dst"]
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0x8f288482},
]
```

2022-05-09 20:13 UTC, jpculp commented on tools/Dockerfile
> +    go mod tidy
```suggestion
RUN \
  sed -i 's,github.com/blizzy78/varnamelen v0.6.1 h1:kttPCLzXFa+0nt++Cw9fb7GrSSM4KkyIAoX/vXsbuqA=,github.com/blizzy78/varnamelen v0.6.1 h1:iYAU/3A6cpfRm2ZI0P/lece4jsc7GEbzsxTu+vBCChQ=,' go.sum ; \
  sed -i 's,github.com/blizzy78/varnamelen v0.6.1/go.mod h1:zy2Eic4qWqjrxa60jG34cfL0VXcSwzUrIx68eJPb4Q8=,github.com/blizzy78/varnamelen v0.6.1/go.mod h1:mGBHm+Uo4e8JnZEKHRoZgVEOQdSBdQfY/x+k4NAXBWA=,' go.sum
R
```
I would just fix the sums manually to keep things simple for now. I'm not sure if we'd rather make this a patch than a `sed` though.

2022-05-09 20:15 UTC, webern commented on tools/Dockerfile
> +    go mod tidy
This seems easier than a patch to me. Thank you I will try this.

2022-05-09 20:26 UTC, webern commented
^ implement @jpculp's fix for the eksctl build

2022-05-09 20:45 UTC, etungsten approved these changes

2022-05-09 20:58 UTC, jpculp approved these changes

2022-05-09 22:48 UTC, webern commented
^ move the date again.

Also, I have re-tested and the new versions of eksctl and sonobuoy are working.

2022-05-10 18:23 UTC, merged