yamlgen: Upgrade serde-yaml to 0.9
bottlerocket-os/bottlerocket-test-system pull request #566
Opened 2022-09-12 23:49 UTC by jpmcb

### Issue number:
Closes #559

### Description of changes:

```
serde-yaml 0.9.x carries a breaking change where `---\n` are not prepended to documents. This patch adds those yaml sperators manually.

Signed-off-by: John McBride <jpmmcb@amazon.com>
```

### Testing done:

`make build` and all is well 👍🏼 

Looks like in [`serde-yaml` 0.9](https://github.com/dtolnay/serde-yaml/releases/tag/0.9.0), they also changed the backend yaml generator which is likely why there are so many formatting changes with this patch: these should be fine regardless 

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-09-14 03:05 UTC, stmcginnis approved these changes
lgtm

2022-09-14 16:24 UTC, mjsterckx commented on yamlgen/build.rs
> +const YAML_SEPERATOR: &str = "---\n";
nit: 
```suggestion
const YAML_SEPARATOR: &str = "---\n";
```

2022-09-14 16:25 UTC, mjsterckx requested changes
Everything else (aside from all of the references to that const) looks good.

2022-09-14 17:14 UTC, stmcginnis approved these changes
Good catch, looks good.

2022-09-14 17:15 UTC, mjsterckx approved these changes

2022-09-15 16:29 UTC, ecpullen commented
Did you try applying the yamlgen files to make validate the generated yaml?

2022-09-20 16:31 UTC, jpmcb commented
Started a new `kind` cluster

```
$ kind create cluster --name serde-test
```

Ensured everything is up to date
```
$ git rev-parse --abbrev-ref HEAD && make build
update-serde
...
```

Apply the yamlgen yaml
```
$ kubectl apply -f yamlgen/deploy
```

Applies fine, but getting the following error:
```
Failed to pull image "6456745674567.dkr.ecr.us-west-2.amazonaws.com/controller:v0.1.2": rpc error: code = Unknown desc = failed to pull and unpack image "6456745674567.dkr.ecr.us-west-2.amazonaws.com/controller:v0.1.2": failed to resolve reference "6456745674567.dkr.ecr.us-west-2.amazonaws.com/controller:v0.1.2": pulling from host 6456745674567.dkr.ecr.us-west-2.amazonaws.com failed with status code [manifests v0.1.2]: 401 Unauthorized
```

Seems there is a hard coded image from an AWS account that isn't public. Closing this PR and we can reconsider if we need `yamlgen` since `setup-test` is available

2022-09-20 16:31 UTC, closed without merging