agent: use Credentials instead of env variables
bottlerocket-os/bottlerocket-test-system pull request #646
Opened 2022-11-04 19:29 UTC by mjsterckx

**Issue number:**

Closes #583 

**Description of changes:**

Changed `aws_test_config` and `aws_resource_config` to store and pass credentials using `Credentials` instead of environment variables. Added bool `setup_env` to both methods to determine whether or not the credentials should be set as environment variables (which should happen when, for example, running `sonobuoy` tests). Added `assume_role_session_duration` argument to `aws_resource_config` which was previously only used in `aws_test_config`. Refactored `aws.rs` to reduce code duplication.

**Testing done:**

Ran an ECS test and an EKS test, both of which passed.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-11-08 01:14 UTC, ecpullen commented on agent/utils/src/aws.rs
> +    setup_env: bool,
Can you add a comment about what this bool does?

2022-11-08 01:14 UTC, ecpullen commented on agent/utils/src/aws.rs
> +            if setup_env {
`if setup_env && assumre_role.is_none()`

2022-11-08 19:33 UTC, mjsterckx commented
^ Addressed ecpullen@ comments

2022-11-08 21:28 UTC, ecpullen requested changes

2022-11-08 21:28 UTC, ecpullen commented on agent/utils/src/aws.rs
> +                    .context(error::CredentialsMissingSnafu { role_arn })?,
~~The session token should not be required.~~
Misread the code.

2022-11-08 21:28 UTC, ecpullen commented on agent/utils/src/aws.rs
> +    aws_secret_name: &&SecretName,
Why is this `&&SecretName`?

2022-11-08 21:28 UTC, ecpullen commented on agent/utils/src/aws.rs
> +        .context(error::SecretMissingSnafu {})?;
Why did the `{}` get added here?

2022-11-08 21:39 UTC, mjsterckx commented
^ Fixed typos

2022-11-08 21:41 UTC, ecpullen approved these changes
🚢

2022-11-21 18:09 UTC, stmcginnis approved these changes
Looks good to me. If not, we can fix it later. ;)

2022-11-21 18:11 UTC, merged